# Generated by Django 5.0.7 on 2024-11-01 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('body', models.CharField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2024, 11, 1, 18, 45, 2, 169167, tzinfo=datetime.timezone.utc))),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
