# Generated by Django 5.0.7 on 2025-02-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
