# Generated by Django 5.0.7 on 2026-06-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
