from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
        ('users', '0011_user_is_admin'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
                    CREATE TABLE IF NOT EXISTS public."quote" (
                        id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        external_id character varying(64),
                        first_name character varying(100) NOT NULL,
                        last_name character varying(100) NOT NULL,
                        email character varying(255) NOT NULL,
                        phone character varying(50),
                        company character varying(255),
                        department character varying(255),
                        service_type character varying(100),
                        timeline character varying(255),
                        budget character varying(255),
                        project_description text,
                        additional_info text,
                        created_at timestamp with time zone DEFAULT now() NOT NULL,
                        read boolean DEFAULT false NOT NULL,
                        CONSTRAINT quote_pkey PRIMARY KEY (id)
                    );

                    ALTER TABLE public."quote"
                    ADD COLUMN IF NOT EXISTS user_id bigint NULL;

                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1
                            FROM pg_constraint
                            WHERE conname = 'quote_user_id_fkey'
                        ) THEN
                            ALTER TABLE public."quote"
                            ADD CONSTRAINT quote_user_id_fkey
                            FOREIGN KEY (user_id)
                            REFERENCES public.users(id)
                            ON DELETE SET NULL;
                        END IF;
                    END $$;

                    CREATE INDEX IF NOT EXISTS quote_user_id_idx
                    ON public."quote" (user_id);
                    ''',
                    reverse_sql='''
                    DROP INDEX IF EXISTS public.quote_user_id_idx;
                    ALTER TABLE public."quote" DROP CONSTRAINT IF EXISTS quote_user_id_fkey;
                    ALTER TABLE public."quote" DROP COLUMN IF EXISTS user_id;
                    ''',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='quote',
                    name='user',
                    field=models.ForeignKey(
                        blank=True,
                        db_column='user_id',
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name='quotes',
                        to='users.user',
                    ),
                ),
            ],
        ),
    ]
