# Generated by Django 5.0.7 on 2025-02-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_body_blog_content_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
