version: '3.8'

services:
  db:
    image: postgres:16
    container_name: bioark_postgres
    restart: always
    environment:
      POSTGRES_DB: bioone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/bioarktech.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bioark_backend
    restart: always
    environment:
      DB_HOST: db
      DB_PASSWORD: postgres
      DEBUG_FLAG: "True"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./media:/var/www/django/media
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bioark_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
