services:
  db:
    image: postgres:16
    container_name: bioark_postgres
    restart: always
    environment:
      POSTGRES_DB: bioone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/bioarktech.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bioone"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bioark_backend
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
      FRONTEND_URL: http://localhost:5173
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./media:/var/www/django/media
      - ./db-conversion:/app/db-conversion
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py migrate --fake-initial &&
             python manage.py collectstatic --noinput;
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8000
    container_name: bioark_frontend
    restart: always
    ports:
      - "5173:80"

    depends_on:
      - backend

volumes:
  postgres_data:
