# Generated by Django 5.0.7 on 2024-11-16 21:04

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_rename_province_address_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('product_sku', models.CharField(max_length=30)),
                ('product_name', models.CharField(default='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('unit_size', models.CharField()),
                ('quantity', models.IntegerField(default=0)),
                ('discount_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_format_code', models.CharField()),
                ('ready_status', models.CharField()),
                ('work_period_earliest', models.IntegerField()),
                ('work_period_latest', models.IntegerField(null=True)),
                ('shipping_temp', models.CharField()),
                ('storage_temp', models.CharField()),
                ('stability_period', models.CharField()),
            ],
            options={
                'db_table': 'work_schedule',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_token', models.CharField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
                ('discount_code', models.CharField(blank=True, null=True)),
                ('order_placed_date', models.DateTimeField(default=datetime.datetime.now)),
                ('order_process_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateField()),
                ('billing_date', models.DateField()),
                ('transaction_status', models.CharField(blank=True, null=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, null=True)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('billing_date', models.DateField()),
                ('transaction_status', models.CharField(blank=True)),
                ('ready_status', models.CharField()),
                ('fulfilled', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=True)),
                ('product_sku', models.CharField(max_length=30)),
                ('product_name', models.CharField(default='Product Name')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjusted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_size', models.CharField()),
                ('quantity', models.IntegerField(default=0)),
                ('discount_code', models.CharField(blank=True, max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.order')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
