# Generated by Django 5.0.7 on 2024-11-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='ready_status',
            field=models.CharField(default='Not'),
            preserve_default=False,
        ),
    ]
