# Generated by Django 5.0.7 on 2024-11-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartitem_ready_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_class',
            field=models.CharField(default='null'),
            preserve_default=False,
        ),
    ]
