# Generated by Django 5.0.7 on 2024-11-23 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_order_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloningCRISPRItem',
            fields=[
            ],
            options={
                'verbose_name': 'Cloning CRISPR Order Item',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='work_period_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 23, 16, 34, 57, 826331)),
            preserve_default=False,
        ),
    ]
