# Generated by Django 5.0.7 on 2024-11-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cloningcrispritem_orderitem_work_period_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloningOverexpressionItem',
            fields=[
            ],
            options={
                'verbose_name': 'Cloning Overexpression Order Item',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
        migrations.CreateModel(
            name='CloningRNAiItem',
            fields=[
            ],
            options={
                'verbose_name': 'Cloning RNAi Order Item',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='bacterial_marker_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='delivery_format_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='fluorescene_marker_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='function_type_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='promoter_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='protein_tag_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selection_marker_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='structure_type_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='target_sequence',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='bacterial_marker_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_format_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fluorescene_marker_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='function_type_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='promoter_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='protein_tag_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selection_marker_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='structure_type_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='target_sequence',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
