# Generated by Django 5.0.7 on 2024-11-24 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_cloningoverexpressionitem_cloningrnaiitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_placed_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_process_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
