# Generated by Django 5.0.7 on 2024-11-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_order_placed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='work_period_date',
            new_name='est_delivery_date',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready For Delivery'), ('finalized', 'Finalized')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='work_period',
            field=models.CharField(default='N/A'),
            preserve_default=False,
        ),
    ]
