# Generated by Django 5.0.7 on 2024-11-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_work_period_date_orderitem_est_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='billing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_date',
            field=models.DateField(null=True),
        ),
    ]
