# Generated by Django 5.0.7 on 2024-12-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_billing_date_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready For Delivery'), ('arrived', 'Arrived')], default='in_progress', max_length=20),
        ),
    ]
