# Generated by Django 5.0.7 on 2025-02-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_billing_address_order_last_digits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_price',
            new_name='shipping_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='subtotal_price',
            new_name='subtotal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tax_price',
            new_name='tax_amount',
        ),
    ]
