# Generated by Django 5.0.7 on 2025-03-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_shipping_price_order_shipping_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='url',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='url',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
