# Generated by Django 5.0.7 on 2025-03-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_cartitem_url_orderitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='est_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='work_period',
            field=models.CharField(blank=True, null=True),
        ),
    ]
