# Generated by Django 5.0.7 on 2025-03-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderitem_est_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='structure_type_code',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='bacterial_marker_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivery_format_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='fluorescene_marker_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='function_type_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='promoter_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='protein_tag_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='selection_marker_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='structure_type_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='target_sequence',
            field=models.CharField(blank=True, null=True),
        ),
    ]
