# Generated by Django 5.0.7 on 2025-03-27 20:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_workschedule_structure_type_code_and_more'),
        ('users', '0008_address_apt_suite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_maximum_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='minimum_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='po_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, blank=True, null=True, related_name='po_orders', to='users.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='po_file',
            field=models.FileField(blank=True, null=True, upload_to='po_files/'),
        ),
        migrations.AddField(
            model_name='order',
            name='po_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_number',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='work_period_latest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_placed_date', models.DateTimeField(default=datetime.datetime.now)),
                ('order_number', models.CharField()),
                ('order_status', models.CharField(default='Effective')),
                ('service_finished', models.BooleanField(default=False)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('billing_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, null=True)),
                ('invoice_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('po_file', models.FileField(blank=True, null=True, upload_to='po_files/')),
                ('po_number', models.CharField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(blank=True, null=True)),
                ('invoice_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_invoices', to='users.address')),
                ('po_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_invoices', to='users.address')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_invoices', to='users.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.invoice'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('quote_number', models.CharField()),
                ('quote_file', models.FileField(upload_to='quote_files/')),
                ('description', models.TextField()),
                ('shelf_status', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('amount', models.CharField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_period_days', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotes',
            },
        ),
    ]
