# Generated by Django 5.0.7 on 2025-03-29 15:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_invoice_amount_order_invoice_maximum_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 29, 10, 34, 0, 890424)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='po_file',
            field=models.FileField(default=None, upload_to='po_files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='po_number',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='receipt_number',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='orders.invoice'),
        ),
    ]
