# Generated by Django 5.0.7 on 2025-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_invoice_billing_date_alter_invoice_invoice_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='po_file',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
