# Generated by Django 5.0.7 on 2025-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_cartitem_quantity_alter_quote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ready_status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
