# Generated by Django 5.0.7 on 2025-04-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_orderitem_discount_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_token',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilled',
            field=models.BooleanField(default=True),
        ),
    ]
