# Generated by Django 5.0.7 on 2025-04-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_invoice_payment_token_alter_order_fulfilled'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalizedOrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking Finalized Order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
        migrations.CreateModel(
            name='InProcessOrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking In Process Order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
        migrations.CreateModel(
            name='OpenOrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking Open Order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('ready_for_delivery', 'Ready For Delivery'), ('invoiced', 'Invoiced'), ('paid', 'Paid')], default='open', max_length=20),
        ),
    ]
