# Generated by Django 5.0.7 on 2025-04-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_finalizedorderitem_inprocessorderitem_openorderitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InProcessOrderItem',
        ),
        migrations.CreateModel(
            name='InProgressOrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking In Progress Order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unit_size',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='work_period_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
