# Generated by Django 5.0.7 on 2025-04-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_delete_inprocessorderitem_inprogressorderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='bacterial_marker_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='delivery_format_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='fluorescene_marker_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='function_type_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='promoter_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='protein_tag_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='selection_marker_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='structure_type_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='target_sequence',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='unit_size',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='url',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_class',
            field=models.CharField(default=''),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_size',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
