# Generated by Django 5.0.7 on 2025-05-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_cartitem_bacterial_marker_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InProgressOrderItem',
        ),
        migrations.CreateModel(
            name='CRISPRInProgressOrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking In Progress CRISPR Order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
        migrations.CreateModel(
            name='OtherInProgressOrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking In Progress Other Order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
        migrations.CreateModel(
            name='OverexpressionInProgressOrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking In Progress Overexpression Order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
        migrations.CreateModel(
            name='ReagentInProgressOrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking In Progress Reagents Order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
        migrations.CreateModel(
            name='RNAiInProgressOrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'Tracking In Progress RNAi Order',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
    ]
