# Generated by Django 5.0.7 on 2025-02-22 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products_union',
            },
        ),
        migrations.CreateModel(
            name='ManualFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual', models.FileField(upload_to='manual_files')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsunion')),
            ],
            options={
                'db_table': 'manual_files',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsunion')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_number', models.CharField()),
                ('product_name', models.CharField()),
                ('description', models.CharField()),
                ('key_features', models.CharField()),
                ('performance_data', models.CharField()),
                ('storage_info', models.CharField()),
                ('shelf_status', models.BooleanField()),
                ('units_in_stock', models.IntegerField()),
                ('units', models.CharField()),
                ('ship_info', models.CharField()),
                ('union', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productsunion')),
            ],
            options={
                'db_table': 'featured_products',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='union',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.productsunion'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UnitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_size', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsunion')),
            ],
            options={
                'db_table': 'unit_prices',
            },
        ),
    ]
