# Generated by Django 5.0.7 on 2025-02-22 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productsunion_manualfile_image_featuredproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='union',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productsunion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='union',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productsunion'),
        ),
    ]
