# Generated by Django 5.0.7 on 2025-02-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_featuredproduct_union_alter_product_union'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsunion',
            name='product_name',
            field=models.CharField(default='Product Name'),
            preserve_default=False,
        ),
    ]
