# Generated by Django 5.0.7 on 2025-02-22 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsunion_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsunion',
            old_name='product_name',
            new_name='product_id',
        ),
    ]
