# Generated by Django 5.0.7 on 2025-02-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_product_name_productsunion_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manualfile',
            name='name',
            field=models.CharField(default='1'),
            preserve_default=False,
        ),
    ]
