# Generated by Django 5.0.7 on 2025-02-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_image_name_manualfile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredproduct',
            old_name='category_number',
            new_name='catalog_number',
        ),
    ]
