# Generated by Django 5.0.7 on 2025-02-23 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_category_number_featuredproduct_catalog_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='on_display',
            field=models.BooleanField(default=False),
        ),
    ]
