# Generated by Django 5.0.7 on 2025-02-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_featuredproduct_on_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='catalog_number',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='key_features',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='performance_data',
            field=models.TextField(),
        ),
    ]
