# Generated by Django 5.0.7 on 2025-02-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_featuredproduct_catalog_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
    ]
