# Generated by Django 5.0.7 on 2025-02-27 23:14

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designlibrary',
            name='adjusted_price',
        ),
        migrations.RemoveField(
            model_name='designlibrary',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='designlibrary',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='designlibrary',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='designlibrary',
            name='ready_status',
        ),
        migrations.AddField(
            model_name='designlibrary',
            name='function_type_code',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designlibrary',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designlibrary',
            name='shelf_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designlibrary',
            name='target_sequence',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designlibrary',
            name='unit',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designlibrary',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='key_features',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='featuredproduct',
            name='performance_data',
            field=tinymce.models.HTMLField(),
        ),
    ]
