# Generated by Django 5.0.7 on 2025-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_designlibrary_adjusted_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designlibrary',
            old_name='unit_size',
            new_name='kit_amount',
        ),
        migrations.AlterField(
            model_name='designlibrary',
            name='list_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
