# Generated by Django 5.0.7 on 2025-03-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_unit_size_designlibrary_kit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designlibrary',
            name='discount_code',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designlibrary',
            name='list_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='designlibrary',
            name='target_sequence',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designlibrary',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
