# Generated by Django 5.0.7 on 2025-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_designlibrary_discount_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylibrary',
            name='function_type',
        ),
        migrations.AddField(
            model_name='deliverylibrary',
            name='function_type_symbol',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
