# Generated by Django 5.0.7 on 2025-03-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_deliverylibrary_function_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promoterspecialcase',
            name='not_both_null',
        ),
        migrations.RemoveField(
            model_name='promoterspecialcase',
            name='structure_type_symbol',
        ),
        migrations.AddField(
            model_name='bacterialmarker',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bacterialmarkerspecialcase',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fluorescenemarker',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promoter',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promoterspecialcase',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proteintag',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='selectionmarker',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='promoterspecialcase',
            name='function_type_symbol',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
