# Generated by Django 5.0.7 on 2025-03-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_bacterialmarker_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuretype',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
