# Generated by Django 5.0.7 on 2025-03-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_structuretype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuretype',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
