# Generated by Django 5.0.7 on 2025-03-08 20:09

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_structuretype_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='storage_info',
            field=tinymce.models.HTMLField(),
        ),
    ]
