# Generated by Django 5.0.7 on 2025-03-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_featuredproduct_storage_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gene',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='serial_id',
        ),
        migrations.AddField(
            model_name='functiontype',
            name='abbreviation',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genelibrary',
            name='abbreviation',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='on_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ship_condition',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='target_sequence',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='units_in_stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structuretype',
            name='abbreviation',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
