# Generated by Django 5.0.7 on 2025-03-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_image_name_remove_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneLibrary',
        ),
    ]
