# Generated by Django 5.0.7 on 2025-03-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_delete_genelibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='on_discount',
            field=models.BooleanField(default=True),
        ),
    ]
