# Generated by Django 5.0.7 on 2025-03-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_featuredproduct_on_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='designlibrary',
            name='on_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='on_discount',
            field=models.BooleanField(default=True),
        ),
    ]
