# Generated by Django 5.0.7 on 2025-03-12 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_designlibrary_on_discount_product_on_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='list_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='adjusted_price',
            new_name='unit_price',
        ),
    ]
