# Generated by Django 5.0.7 on 2025-03-12 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_rename_base_price_product_list_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functiontype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
