# Generated by Django 5.0.7 on 2025-03-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_functiontype_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='on_display',
            new_name='main_display',
        ),
        migrations.RenameField(
            model_name='unitprice',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AddField(
            model_name='unitprice',
            name='list_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
