# Generated by Django 5.0.7 on 2025-03-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_rename_on_display_image_main_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitprice',
            name='on_discount',
            field=models.BooleanField(default=True),
        ),
    ]
