# Generated by Django 5.0.7 on 2025-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_unitprice_on_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functiontype',
            name='category',
            field=models.CharField(),
        ),
    ]
