# Generated by Django 5.0.7 on 2025-03-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_functiontype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='functiontype',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
