# Generated by Django 5.0.7 on 2025-03-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_featuredproduct_priority_functiontype_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
