# Generated by Django 5.0.7 on 2025-05-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_productcategory_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryformat',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
