# Generated by Django 5.0.7 on 2026-06-22 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.TextField()),
            ],
            options={
                'db_table': 'img',
            },
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_images_association',
        ),
        migrations.AddField(
            model_name='product',
            name='images_relation',
            field=models.ManyToManyField(blank=True, through='products.ProductImage', to='products.img'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='img',
            field=models.ForeignKey(db_column='img_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.img'),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'img')},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
    ]
