# Generated by hand
from django.db import migrations

def set_default_featured_products(apps, schema_editor):
    pass

def remove_default_featured_products(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_load_old_consumables'),
    ]

    operations = [
        migrations.RunPython(set_default_featured_products, remove_default_featured_products),
    ]
