# Generated by hand

from django.db import migrations

def set_default_featured_products(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    featured_ids = ['cleancap-egfp-mrna', 'BADM3367', 'hot-start-ttx-dna-polymerase', 'BADM3363', 'vc-01']
    Product.objects.filter(external_id__in=featured_ids).update(is_featured=True)

def remove_default_featured_products(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    featured_ids = ['cleancap-egfp-mrna', 'BADM3367', 'hot-start-ttx-dna-polymerase', 'BADM3363', 'vc-01']
    Product.objects.filter(external_id__in=featured_ids).update(is_featured=False)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0038_load_old_consumables'),
    ]

    operations = [
        migrations.RunPython(set_default_featured_products, remove_default_featured_products),
    ]
