# Generated by hand
from django.db import migrations

def insert_homepage_mock_products(apps, schema_editor):
    pass

def remove_homepage_mock_products(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_set_default_featured_products'),
    ]

    operations = [
        migrations.RunPython(insert_homepage_mock_products, remove_homepage_mock_products),
    ]
