# Generated by hand

from django.db import migrations

def insert_homepage_mock_products(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ProductCategory = apps.get_model('products', 'ProductCategory')
    
    cat = ProductCategory.objects.filter(external_id='category-1780539818236').first()

    mock_products_data = [
        {
            'product_name': 'BioArk Agarose LE (Low EEO) High Strength',
            'external_id': 'bioark-agarose-le',
            'catalog_number': 'AG-LE100',
            'list_price': '29.00',
            'availability': 'In Stock',
            'description': 'High-purity agarose optimized for analytical and preparative nucleic acid electrophoresis.',
            'source_type': 'mock',
            'is_featured': True
        },
        {
            'product_name': 'Premium dNTP Mix (2.5 mM each)',
            'external_id': 'premium-dntp-mix',
            'catalog_number': 'DNTP-25',
            'list_price': '29.00',
            'availability': 'In Stock',
            'description': 'Ultra-pure dNTP mix designed for robust and consistent PCR amplification.',
            'source_type': 'mock',
            'is_featured': True
        },
        {
            'product_name': 'Cas9 Nuclease (S. pyogenes) Recombinant',
            'external_id': 'cas9-nuclease-s-pyogenes',
            'catalog_number': 'CAS9-SP',
            'list_price': '89.00',
            'availability': 'In Stock',
            'description': 'Recombinant Streptococcus pyogenes Cas9 protein for highly efficient genome editing.',
            'source_type': 'mock',
            'is_featured': True
        },
        {
            'product_name': 'NEB CutSmart Buffer (10X)',
            'external_id': 'neb-cutsmart-buffer',
            'catalog_number': 'BUF-CS',
            'list_price': '19.00',
            'availability': 'In Stock',
            'description': '10X buffer optimized for maximum restriction endonuclease activity.',
            'source_type': 'mock',
            'is_featured': True
        },
        {
            'product_name': 'Protein Ladder (10-250 kDa) Ready-to-Use',
            'external_id': 'protein-ladder-10-250',
            'catalog_number': 'PROT-LAD',
            'list_price': '29.00',
            'availability': 'In Stock',
            'description': 'Prestained protein ladder covering molecular weights from 10 to 250 kDa.',
            'source_type': 'mock',
            'is_featured': True
        },
        {
            'product_name': '1 kb Plus DNA Ladder (0.1-10 kb)',
            'external_id': '1-kb-plus-dna-ladder',
            'catalog_number': 'DNA-LAD-1KBP',
            'list_price': '25.00',
            'availability': 'In Stock',
            'description': 'Ready-to-use DNA ladder for size determination of PCR and restriction fragments.',
            'source_type': 'mock',
            'is_featured': True
        },
        {
            'product_name': 'Plasmid Mini Prep Kit (50 preps)',
            'external_id': 'plasmid-mini-prep-kit',
            'catalog_number': 'KIT-PMP50',
            'list_price': '49.00',
            'availability': 'In Stock',
            'description': 'Fast and efficient spin-column based purification of high-quality plasmid DNA.',
            'source_type': 'mock',
            'is_featured': True
        },
        {
            'product_name': 'BioArkTech Gel Documentation System (1200W)',
            'external_id': 'bioarktech-gel-doc-system',
            'catalog_number': 'EQ-GD1200',
            'list_price': '3299.00',
            'availability': 'In Stock',
            'description': 'High-resolution gel imaging system equipped with 1200W UV/blue transilluminator.',
            'source_type': 'mock',
            'is_featured': True
        }
    ]

    for item in mock_products_data:
        p, created = Product.objects.get_or_create(
            external_id=item['external_id'],
            defaults={
                'product_name': item['product_name'],
                'catalog_number': item['catalog_number'],
                'list_price': item['list_price'],
                'availability': item['availability'],
                'description': item['description'],
                'source_type': item['source_type'],
                'is_featured': item['is_featured'],
                'category': cat,
                'category_external_id': cat.external_id if cat else None
            }
        )
        if not created:
            p.is_featured = True
            p.save()

def remove_homepage_mock_products(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    featured_ids = [
        'bioark-agarose-le', 'premium-dntp-mix', 'cas9-nuclease-s-pyogenes', 
        'neb-cutsmart-buffer', 'protein-ladder-10-250', '1-kb-plus-dna-ladder', 
        'plasmid-mini-prep-kit', 'bioarktech-gel-doc-system'
    ]
    Product.objects.filter(external_id__in=featured_ids).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_set_default_featured_products'),
    ]

    operations = [
        migrations.RunPython(insert_homepage_mock_products, remove_homepage_mock_products),
    ]
