# Generated by Django 5.0.7 on 2026-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_insert_homepage_mock_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_screen',
            field=models.BooleanField(default=False),
        ),
    ]
