# Generated by hand
from django.db import migrations

def set_show_on_screen(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_product_show_on_screen'),
    ]

    operations = [
        migrations.RunPython(set_show_on_screen),
    ]
