# Generated by hand
from django.db import migrations

def fix_product_prices(apps, schema_editor):
    pass

def reverse_fix_product_prices(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_set_default_show_on_screen'),
    ]

    operations = [
        migrations.RunPython(fix_product_prices, reverse_fix_product_prices),
    ]
