# Generated by hand
from django.db import migrations

def remove_ghost_products(apps, schema_editor):
    pass

def reverse_remove_ghost_products(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_fix_product_prices'),
    ]

    operations = [
        migrations.RunPython(remove_ghost_products, reverse_remove_ghost_products),
    ]
