# Generated by Django 5.0.7 on 2025-03-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneLibrary',
            fields=[
                ('gene_library_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_sequence', models.CharField(max_length=6)),
                ('gene_name', models.CharField()),
                ('abbreviation', models.CharField(blank=True, null=True)),
                ('symbol', models.CharField()),
                ('locus_id', models.IntegerField(null=True)),
                ('species', models.CharField(null=True)),
                ('description', models.CharField(blank=True, null=True)),
                ('reference_link', models.CharField(null=True)),
            ],
            options={
                'db_table': 'gene_library',
            },
        ),
    ]
