# Generated by Django 5.0.7 on 2025-02-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField()),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'product_mode',
            },
        ),
        migrations.CreateModel(
            name='ServiceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField()),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'service_mode',
            },
        ),
    ]
