# Generated by Django 5.0.7 on 2025-02-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmode',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='servicemode',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
