# Generated by Django 5.0.7 on 2025-03-14 20:02

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_alter_productmode_title_alter_servicemode_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmode',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='servicemode',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
