# Generated by Django 5.0.7 on 2025-03-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_alter_productmode_content_alter_servicemode_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmode',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicemode',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
