# Generated by Django 5.0.7 on 2025-03-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_productmode_raw_html_servicemode_raw_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmode',
            name='raw_html',
        ),
        migrations.RemoveField(
            model_name='servicemode',
            name='raw_html',
        ),
        migrations.AddField(
            model_name='productmode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='servicemode',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
