# Generated by Django 5.0.7 on 2026-06-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_remove_productmode_raw_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemode',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
