# Generated by Django 5.0.7 on 2026-06-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_servicemode_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSlide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eyebrow', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_button_link', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'homepage_slide',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
