# Generated by hand
from django.db import migrations
import os
import json
import re

CATEGORY_MAPPING = {
    'genome-editing-service': {
        'id': 'genome-editing-services',
        'name': 'Genome Editing Services'
    },
    'synthesis-cloning': {
        'id': 'synthesis-cloning-services',
        'name': 'Custom Cloning Services'
    },
    'virus-packaging': {
        'id': 'virus-packaging-services',
        'name': 'Lentivirus Package Services'
    },
    'cell-line-services': {
        'id': 'cell-line-services',
        'name': 'Stable Cell Line Services'
    },
    'category-1764976659245': {
        'id': 'protein-purification-services',
        'name': 'Protein Purification Services'
    }
}

def markdown_to_html(md):
    if not md:
        return ""
    html = md
    html = html.replace('\r\n', '\n').replace('\r', '\n')
    
    # Headers
    html = re.sub(r'^###### (.*?)$', r'<h6>\1</h6>', html, flags=re.MULTILINE)
    html = re.sub(r'^##### (.*?)$', r'<h5>\1</h5>', html, flags=re.MULTILINE)
    html = re.sub(r'^#### (.*?)$', r'<h4>\1</h4>', html, flags=re.MULTILINE)
    html = re.sub(r'^### (.*?)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
    html = re.sub(r'^## (.*?)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
    html = re.sub(r'^# (.*?)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
    
    # Tables
    lines = html.split('\n')
    in_table = False
    table_html = []
    new_lines = []
    for line in lines:
        if line.strip().startswith('|'):
            if not in_table:
                in_table = True
                table_html.append('<table class="table table-bordered">')
                cols = [c.strip() for c in line.split('|')[1:-1]]
                table_html.append('<thead><tr>' + ''.join(f'<th>{c}</th>' for c in cols) + '</tr></thead>')
                table_html.append('<tbody>')
            else:
                if '---' in line:
                    continue
                cols = [c.strip() for c in line.split('|')[1:-1]]
                table_html.append('<tr>' + ''.join(f'<td>{c}</td>' for c in cols) + '</tr>')
        else:
            if in_table:
                in_table = False
                table_html.append('</tbody></table>')
                new_lines.append('\n'.join(table_html))
                table_html = []
            new_lines.append(line)
    if in_table:
        table_html.append('</tbody></table>')
        new_lines.append('\n'.join(table_html))
    html = '\n'.join(new_lines)
    
    # Bold / Italics
    html = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', html)
    html = re.sub(r'__(.*?)__', r'<strong>\1</strong>', html)
    html = re.sub(r'\*(.*?)\*', r'<em>\1</em>', html)
    
    # Lists
    lines = html.split('\n')
    in_list = False
    list_html = []
    new_lines2 = []
    for line in lines:
        striped = line.strip()
        if striped.startswith('- ') or striped.startswith('* '):
            item = striped[2:]
            if not in_list:
                in_list = True
                list_html.append('<ul>')
            list_html.append(f'<li>{item}</li>')
        else:
            if in_list:
                in_list = False
                list_html.append('</ul>')
                new_lines2.append('\n'.join(list_html))
                list_html = []
            new_lines2.append(line)
    if in_list:
        list_html.append('</ul>')
        new_lines2.append('\n'.join(list_html))
    html = '\n'.join(new_lines2)
    
    # Links
    html = re.sub(r'\[(.*?)\]\((.*?)\)', r'<a href="\2">\1</a>', html)
    
    # Paragraphs wrapping
    lines = html.split('\n')
    new_lines3 = []
    for line in lines:
        striped = line.strip()
        if not striped:
            continue
        if striped.startswith('<') and (striped.endswith('>') or striped.endswith('</p>')):
            new_lines3.append(striped)
        else:
            new_lines3.append(f'<p>{striped}</p>')
    html = '\n'.join(new_lines3)
    
    return html

def load_services_from_json(apps, schema_editor):
    ServiceMode = apps.get_model('interface', 'ServiceMode')
    ProductCategory = apps.get_model('products', 'ProductCategory')
    
    # Clear existing services loaded by migrations 0008
    ServiceMode.objects.all().delete()
    
    # Locate services.json
    possible_paths = [
        os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), 'services.json'),
        os.path.join(os.path.dirname(os.path.abspath(__file__)), 'services.json'),
        '/app/services.json',
        'services.json',
    ]
    
    json_path = None
    for path in possible_paths:
        if os.path.exists(path):
            json_path = path
            break
            
    if not json_path:
        raise FileNotFoundError("Could not locate services.json in migrations loader.")
        
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    categories_data = data.get("categoriesConfig", {}).get("categories", [])
    overrides = data.get("overrides", {})
    custom = data.get("custom", [])
    
    # Create categories
    for cat in categories_data:
        cat_id = cat['id']
        cat_name = cat['name']
        cat_order = cat.get('order', 1)
        
        if cat_id in CATEGORY_MAPPING:
            m = CATEGORY_MAPPING[cat_id]
            cat_id = m['id']
            cat_name = m['name']
            
        ProductCategory.objects.update_or_create(
            external_id=cat_id,
            defaults={
                'category_name': cat_name,
                'priority': cat_order,
                'product_type': 'service'
            }
        )
        
    services_to_insert = []
    
    # - Process Overrides
    for key, val in overrides.items():
        if val.get('hidden') is True and not val.get('name'):
            continue
            
        link = val.get('link')
        if not link:
            continue
            
        url_slug = link.replace('/services/', '')
        content_html = markdown_to_html(val.get('markdown', ''))
        
        img_url = val.get('imageUrl', '')
        django_image_name = ''
        if img_url:
            filename = os.path.basename(img_url)
            django_image_name = f"service_images/{filename}"
            
        is_featured = val.get('showInHomepageServices', False)
        show_on_screen = not val.get('hidden', False)
        
        cat_id = val.get('category')
        if cat_id in CATEGORY_MAPPING:
            cat_id = CATEGORY_MAPPING[cat_id]['id']
            
        services_to_insert.append({
            'url': url_slug,
            'title': val.get('name', ''),
            'content': content_html,
            'image': django_image_name,
            'category': cat_id,
            'is_featured': is_featured,
            'show_on_screen': show_on_screen
        })
        
    # - Process Custom
    for c in custom:
        link = c.get('link')
        if not link:
            continue
            
        url_slug = link.replace('/services/', '')
        content_html = markdown_to_html(c.get('markdown', ''))
        
        img_url = c.get('imageUrl', '')
        django_image_name = ''
        if img_url:
            filename = os.path.basename(img_url)
            django_image_name = f"service_images/{filename}"
            
        is_featured = c.get('showInHomepageServices', False)
        show_on_screen = not c.get('hidden', False)
        
        cat_id = c.get('category')
        if cat_id in CATEGORY_MAPPING:
            cat_id = CATEGORY_MAPPING[cat_id]['id']
            
        services_to_insert.append({
            'url': url_slug,
            'title': c.get('name', ''),
            'content': content_html,
            'image': django_image_name,
            'category': cat_id,
            'is_featured': is_featured,
            'show_on_screen': show_on_screen
        })
        
    for s_data in services_to_insert:
        ServiceMode.objects.create(
            url=s_data['url'],
            title=s_data['title'],
            content=s_data['content'],
            image=s_data['image'] if s_data['image'] else None,
            category=s_data['category'],
            is_featured=s_data['is_featured'],
            show_on_screen=s_data['show_on_screen']
        )

def unload_services_from_json(apps, schema_editor):
    ServiceMode = apps.get_model('interface', 'ServiceMode')
    ServiceMode.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_populate_services_and_slides'),
    ]

    operations = [
        migrations.RunPython(load_services_from_json, unload_services_from_json),
    ]
