# Generated by Django 5.0.7 on 2026-07-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_populate_services_from_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemode',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
