# Generated by hand

from django.db import migrations

def set_default_featured_services(apps, schema_editor):
    ServiceMode = apps.get_model('interface', 'ServiceMode')
    featured_urls = ['lentivirus-package', 'custom-cloning', 'stable-cell-line', 'aav-packaging-services']
    ServiceMode.objects.filter(url__in=featured_urls).update(is_featured=True)

def remove_default_featured_services(apps, schema_editor):
    ServiceMode = apps.get_model('interface', 'ServiceMode')
    featured_urls = ['lentivirus-package', 'custom-cloning', 'stable-cell-line', 'aav-packaging-services']
    ServiceMode.objects.filter(url__in=featured_urls).update(is_featured=False)

class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_servicemode_is_featured'),
    ]

    operations = [
        migrations.RunPython(set_default_featured_services, remove_default_featured_services),
    ]
