# Generated by Django 5.0.7 on 2026-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_set_default_featured_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemode',
            name='category',
        ),
        migrations.AddField(
            model_name='servicemode',
            name='show_on_screen',
            field=models.BooleanField(default=False),
        ),
    ]
