# Generated by Django 5.0.7 on 2026-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_remove_servicemode_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemode',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
