# Generated by Django 5.0.7 on 2026-08-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0022_servicemode_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('port', models.IntegerField(default=465)),
                ('secure', models.BooleanField(default=True)),
                ('user', models.EmailField(default='wulipeng@gmail.com', max_length=254)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('from_email', models.EmailField(default='wulipeng@gmail.com', max_length=254)),
                ('admin_to_emails', models.CharField(default='Lipengwu@bioarktech.com', max_length=500)),
                ('full_subject', models.CharField(default='New Quote (Full) from {{firstName}} {{lastName}} — {{serviceType}}', max_length=255)),
                ('full_body', models.TextField(default='<h2>New Quote (Full) Notification</h2>\n<p><strong>Name:</strong> {{firstName}} {{lastName}}</p>\n<p><strong>Email:</strong> {{email}}</p>\n{{#if phone}}<p><strong>Phone:</strong> {{phone}}</p>{{/if}}\n<p><strong>Company:</strong> {{company}}</p>\n{{#if department}}<p><strong>Department:</strong> {{department}}</p>{{/if}}\n<p><strong>Service:</strong> {{serviceType}}</p>\n<p><strong>Description:</strong> {{projectDescription}}</p>')),
                ('product_subject', models.CharField(default='New Product Quote from {{firstName}} {{lastName}}', max_length=255)),
                ('product_body', models.TextField(default='<h2>New Product Quote</h2>\n<p><strong>Name:</strong> {{firstName}} {{lastName}}</p>\n<p><strong>Email:</strong> {{email}}</p>\n<hr/>\n<p><strong>Product:</strong> {{projectDescription}}</p>\n{{#if catalogNumber}}<p><strong>Catalog #:</strong> {{catalogNumber}}</p>{{/if}}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'smtp_config',
            },
        ),
    ]
