# Generated by Django 5.0.7 on 2026-08-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0023_smtpconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpconfig',
            name='google_client_id',
            field=models.CharField(blank=True, default='1047155694294-1a3b4c5d6e7f8g9h0i.apps.googleusercontent.com', max_length=255),
        ),
    ]
