# Generated by Django 5.0.7 on 2026-08-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0024_smtpconfig_google_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpconfig',
            name='google_client_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='google_refresh_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='sender_email',
            field=models.EmailField(default='wulipeng@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='smtpconfig',
            name='use_google_oauth',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='smtpconfig',
            name='google_client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
