# Generated by Django 5.0.7 on 2024-11-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_address_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='province',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(null=True),
        ),
    ]
