# Generated by Django 5.0.7 on 2024-12-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_has_set_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
