# Generated by Django 5.0.7 on 2025-02-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apt_suite',
            field=models.CharField(null=True),
        ),
    ]
