# Generated by Django 5.0.7 on 2025-05-29 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_address_alter_user_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='apt_suite',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='US', null=True),
        ),
    ]
